### ISSUE TITLE
CMake paths not correct

### ISSUE THREAD

**Issue by ShamanTcler** [janwilmans/copperspice-gettingstarted#10]
Platform: Win 10 , MSVS 2017, cmake  3.15.4,  nuget installed CS 1.6.1

Error message: 
```
 The imported target "CopperSpice::CsCore" references the file    "C:/Users/xxx/.nuget/packages/copperspice/1.6.1/build/native/copperspice/lib/CsCore1.6.lib"
  but this file does not exist.
```

the correct path is:
C:/Users/xxx/.nuget/packages/copperspice/1.6.1/build/native/copperspice/**_release_**/lib/CsCore1.6.lib

**Comment by ShamanTcler** [comment]
By the way this is CandL from the forums

**Comment by janwilmans** [comment]
thanks again for reporting, I fixed this long ago, but forgot to give feedback here; closing now.
