### ISSUE TITLE
question on building copperspice

### ISSUE THREAD

**Issue by mediabuff** [janwilmans/copperspice-gettingstarted#11]
Hello,
How did you build 1.6  ? I trying to build using cmake and VS2019, get ton of errors because of winsock2.h . As you know this conflicts with winsock.h in windows.h - which is used profusely in copperspice code base.

**Comment by janwilmans** [comment]
In used these scripts to configure cmake:
https://github.com/janwilmans/copperspice-gettingstarted/blob/master/configure-x64-v142-runtime.bat

If you tell me how you did it, I might be able to see what goes wrong.
One of the thinks that I found was that have vcpkg installed can cause cmake to find weird combinations of packages, that aren't actually needed to build on windows. So maybe check if the cmake generation step finds certains packages through vcpkg, and if so move them out of the way :)

**Comment by mediabuff** [comment]
I used the IDE. VS2019 now has great support for cmake .  Could you pl try that. I will try your cmd script.

Regarding vcpkg, it had trouble with zlib and also was not properly adding vcpkg include directory.

I also see 2 problems with CS

 Vcpkg include is supposed to be added by the consuming cmake - thru findpkg - which I didn’t see in CS cmake files.

Additionally, there is a flaw in CS source files. It includes windows.h without lean-and-mean. This will pull in winsock.h and conflict with winsock2.h.

**Comment by janwilmans** [comment]
VS2019 's cmake support works, I use it for copperspice as well. Compiling Copperspice is easier if you take vcpkg out to start with. It is not required to build copperspice.

**Comment by mediabuff** [comment]
Thank you for your online support. Was able to successfully build copperspice and kitchensink using VS2019 IDE based cmake !!

**Comment by janwilmans** [comment]
Glad to be of service! Cheers!
