### ISSUE TITLE
CompiledUIControl build error in VS2019

### ISSUE THREAD

**Issue by mediabuff** [janwilmans/copperspice-gettingstarted#12]
..\copperspice-gettingstarted\visual studio 2019\CompiledUIControl\CompiledUIControl.vcxproj : error  : File D:\MyDevProjects\MyProjectsThirdPartySamples\copperspice-gettingstarted\visual studio 2019\CompiledUIControl\mainwindow.ui is included into CustomBuild and None item groups. This is not allowed for project items, which can belong to only one item group.

**Comment by janwilmans** [comment]
I will look into this, thanks for reporting

**Comment by janwilmans** [comment]
this can happen after a failed upgrade from a previous version; remove and re-add the copperspice nuget package, and it works again.
